package main

import (
	"flag"
	"log"
	"os"

	"github.com/jguillaumes/go-genencode/internal/tablemgr"
)

func main() {
	log.SetFlags(log.LstdFlags | log.Lshortfile)

	table := flag.String("table", "", "The decoding table generated by CodecMapper")
	flag.Parse()

	if *table == "" {
		flag.Usage()
		os.Exit(1)
	}

	tableFile, err := os.Open(*table)
	if err != nil {
		log.Fatalln(err)
	}
	defer tableFile.Close()

	dect, ok, nok, comm, err := tablemgr.GenerateDecoder(tableFile)
	if err != nil {
		log.Fatalln(err)
	}
	log.Printf("Parsed %s table: %d comment lines, %d valid lines, ignored %d bad lines\n", *table, comm, ok, nok)
	decoderString := tablemgr.GenerateEBCDICtoASCII(dect, "TABLE", true)
	print(decoderString)
}
